version: '3'

output: prefixed

vars:
  PACKAGE: tagger
  VERSION:
    sh: cat "src/{{.PACKAGE}}/__version__"
  CONDA:
    # Use mamba if available
    sh: if ! command -v mamba &> /dev/null; then echo conda; else echo mamba; fi
  CONDABUILD:
    # Use mambabuild if boa is installed
    sh: if [ -z "$(conda list | grep boa)" ]; then echo build; else echo mambabuild; fi
  DEVDEPS: anaconda-client twine 

tasks:
  install-dev-deps:
    desc: Install development dependencies.
    cmds:
      - echo "{{.CONDA}} install {{.DEVDEPS}}"

  build:
    desc: Build the Conda package.
    cmds:
      - conda {{.CONDABUILD}} {{.CHANNELS}} --output-folder dist pkg
    vars:
      CHANNELS: "-c defaults -c conda-forge"

  upload:
    desc: Upload package to anaconda.org.
    cmds:
      - anaconda upload "dist/noarch/{{.PACKAGE}}-{{.VERSION}}-py_0.tar.bz2"

  clean:
    desc: Remove all build artifacts.
    cmds:
      - rm -rf dist/* dist/.*
      - rm -rf build/* build/.*
