{% set data = load_setup_py_data() %}

package:
  name: tagger
  version: {{ data.get('version') }}

source:
  git_url: ".."

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python>=3.6
    - pip
  run:
    - python>=3.6
    - numpy

test:
  imports:
    - tagger
  requires:
    - pytest
  source_files:
    - test
  commands:
    - pytest -W ignore::DeprecationWarning

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
